#!/usr/bin/python3

from sys import argv

def factorize(number):
    for i in range(2, int(number**0.5) + 1):
        if number % i == 0:
            return f"{number}={i}*{number//i}"
    return f"{number} is a prime number"

def main(filename):
    with open(filename, 'r') as file:
        numbers = file.read().splitlines()

    for number in numbers:
        factorization = factorize(int(number))
        print(factorization)

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: ./factors <file>")
        sys.exit(1)

    main(sys.argv[1])
