#!/usr/bin/python3

import sys


def is_prime(number):
    if number <= 1:
        return False
    if number <= 3:
        return True
    if number % 2 == 0 or number % 3 == 0:
        return False
    i = 5
    while i * i <= number:
        if number % i == 0 or number % (i + 2) == 0:
            return False
        i += 6
    return True


def find_prime_factors(number):
    for i in range(2, int(number**0.5) + 1):
        if number % i == 0:
            if is_prime(i) and is_prime(number // i):
                return i, number // i
    return None, None


def main(filename):
    with open(filename, 'r') as file:
        number = int(file.read().strip())

    p, q = find_prime_factors(number)
    if p and q:
        print(f"{number}={p}*{q}")
    else:
        print(f"Unable to find prime factors for {number}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: ./factors <file>")
        sys.exit(1)

    main(sys.argv[1])
